google_dfp_plugin:
  dfp_id:
    client: true
    default: ''

  dfp_show_topic_list_top:
    client: true
    default: false
  dfp_topic_list_top_code:
    client: true
    default: ''

  dfp_show_topic_top:
    client: true
    default: false
  dfp_topic_top_code:
    client: true
    default: ''

  dfp_show_topic_bottom:
    client: true
    default: false
  dfp_topic_bottom_code:
    client: true
    default: ''

  dfp_mobile_show_topic_list_top:
    client: true
    default: false
  dfp_mobile_topic_list_top_code:
    client: true
    default: ''

  dfp_mobile_show_topic_top:
    client: true
    default: false
  dfp_mobile_topic_top_code:
    client: true
    default: ''

  dfp_mobile_show_topic_bottom:
    client: true
    default: false
  dfp_mobile_topic_bottom_code:
    client: true
    default: ''
